<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>EZT Template Bundle for TextMate by Daniel O'Brien, 2007.</string>
	<key>fileTypes</key>
	<array>
		<string>ezt</string>
	</array>
	<key>firstLineMatch</key>
	<string>\[</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		\[\s*(?:if-any|if-index|if|is|for|define).*?\]
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		\[\s*(?:end).*?\]
		)</string>
	<key>keyEquivalent</key>
	<string>^~E</string>
	<key>name</key>
	<string>EZT</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\[\[\]</string>
			<key>name</key>
			<string>constant.character.escape.squarebracket</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[#</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>comment.block.ezt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>contentName</key>
			<string>entity.function.ezt</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.tag.any.ezt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if-any|if-index|if|else|for|is|end|format|include|insertfile|define)\b</string>
					<key>name</key>
					<string>keyword.control.ezt</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(odd|even|first|last)\b</string>
					<key>name</key>
					<string>constant.language.ezt</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>insertfile</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ezt</string>
	<key>uuid</key>
	<string>A1C730E5-24DB-43DB-A26B-C61A15D61A54</string>
</dict>
</plist>
